config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  devise_for :users
  resources :transactions
  resources :categories
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splash#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions, dependent: :destroy
  has_one_attached :icon
  belongs_to :user

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :Categories, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :transactions, foreign_key: :author_id
  has_many :categories

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:transactions).all
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = current_user.categories.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions or /transactions.json
  def index
    @category = Category.find(params[:category_id])
    @transactions = @category.transactions.order(created_at: :desc)
    @total = @category.transactions.sum(:amount)
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.create(transaction_params)
    @transaction.author = current_user

    respond_to do |format|
      if @transaction.save
        format.html do
          redirect_to transactions_path(transaction_category), notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id)
  end

  def transaction_category
    params.require(:transaction).permit(:category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= link_to transactions_path(category_id: category.id), class: "card-link" do %>
    <div class="category-card sign-color">
      <%= image_tag(category.icon, class: "category-image") %>
      <%= category.name %>
      <p><%= category.transactions.sum(:amount)%></p>
    </div>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <div class="new-save">
    <div class="actions">
      <%= form.submit "Save", class: "registration-button" %>
    </div>
  </div>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="sign-color">
    <div class="field form-div">
      <% form.label :name, style: "display: block"%>
      <%= form.text_field :name, id: "Name", placeholder: "Name", class: "form-input" %>
    </div>

    <div class="field form-div">
      <%= form.label :icon, id: "Icon", style: "display: block" %>
      <%= form.file_field :icon %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>
<%= render "form", category: @category %>
<br>
<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<main class="main-style">
  <%= render partial: 'partials/header', locals: { page: 'Categories' } %>
  <p style="color: green"><%= notice %></p>

  <div id="categories">
    <% if @categories.empty? %>
      <div class="message">There are no categories to display. Add one.</div>
    <% else %>
      <% @categories.each do |category| %>
        <%= render category %>
      <% end %>
    <% end %>
  </div>

  <div class= "btn-div" >
    <%= link_to "New category", new_category_path, class: "category-btn" %>
  </div>
</main>

app/views/categories/new.html.erb
<div class="new-head">
  <%= link_to categories_path, class: "back-link" do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
    <p>New Category</p>
    <i class="bi bi-list"></i>
</div>
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @category %>
<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>
  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "splash", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "signup", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "header", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="height" >
    <main class="height">
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_header.html.erb
<nav class="header-color">
  <div class="header-arrange">
    <i class="bi bi-list"></i>
    <p><%= page %></p>
    <i class="bi bi-search"></i>
  </div>
  <div class="link-arrange">
    <%= link_to "sign out", destroy_user_session_path, method: :delete, class: "header-link" %>
  </div>
</nav>

app/views/splash/index.html.erb
<div class="height splash-flex">
  <h1 class="fonts" >Budget App</h1>
  <div class="bottom splash-buttons">
    <%= link_to "LOG IN", new_user_session_path, class: "splash-login" %>
    <%= link_to "SIGN UP", new_user_registration_path, class: "splash-signup sign-color" %>
  </div>
</div>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <div class="new-save">
    <div class="actions">
      <%= form.submit "Save", class: "registration-button" %>
    </div>
  </div>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="sign-color">
    <div class="field form-div">
      <% form.label :name, id: "Name", style: "display: block" %>
      <%= form.text_field :name, placeholder: "Name", class: "form-input" %>
    </div>

    <div class="field form-div">
      <%= form.label :amount, id: "Amount", style: "display: block" %>
      <%= form.text_field :amount, type: :number, class: "form-input" %>
    </div>

    <div class="field form-div">
      <%= form.select :category_id, options_for_select([['Select a category', '']] + Category.all.map { |c| [c.name, c.id] }), {}, { class: "form-input" } %>
    </div>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div class="transaction-card">
  <%= transaction.name %> <br>
<%= transaction.created_at.strftime('%d-%B-%Y') %>
  <p>
    $ <%= transaction.amount %>
  </p>
  
</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>
<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<div class="new-head">
  <%= link_to categories_path, class: "back-link" do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
    <p>Transactions</p>
    <i class="bi bi-list"></i>
</div>
<div class="transaction-total">
  <p>Total Amount: <%= @total %></p>
  <%= link_to "sign out", destroy_user_session_path, method: :delete, class: "header-link" %>
</div>
<p style="color: green"><%= notice %></p>

<div id="transactions">
  <% if @transactions.empty? %>
      <div class="message">There are no transactions to display. Add one.</div>
    <% else %>
    <% @transactions.each do |transaction| %>
      <%= render transaction %>
    <% end %>
  <% end %>
</div>

<div class= "btn-div" >
  <%= link_to "New transaction", new_transaction_path, class: "category-btn" %>
</div>

app/views/transactions/new.html.erb
<div class="new-head">
  <%= link_to transactions_path(category_id: 1), class: "back-link" do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
    <p>New Transaction</p>
    <i class="bi bi-list"></i>
</div>

<%= render "form", transaction: @transaction %>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @transaction %>
<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>
  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>